server:
  port: ${PORT:8080}

spring:
  application:
    name: ai-proxy

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO

app:

  security:
    enabled: true
    allowed-ips: ${ALLOWED_IPS:}
    admin-token: ${ADMIN_TOKEN:}
    dynamic-ip-ttl-minutes: 720

  providers-json: ${PROVIDERS_JSON:{}}